version: 1.0
app:
  instances:
    min: 1
    max: 2
  env:
    - name: JVM_ARGS
      value: "-DenvironmentType=stage"
  variables:
    - name: discoveryEndpoint
      value: "CHANGE_ME"
    - name: clientId
      value: "CHANGE_ME"
  version: "bcf08040-1c7d-4e87-b4a5-1d02bcdec1fe"
  java: 17
