version: 1.0
app:
  instances:
    min: 1
    max: 2
  env:
    - name: JVM_ARGS
      value: "-DenvironmentType=stage"
  variables:
    - name: discoveryEndpoint
      value: "CHANGE_ME"
    - name: clientId
      value: "CHANGE_ME"
  version: "cc31cb16-30eb-4b5d-8aae-46693d41b894"
  java: 17
